# Generated by Django 2.2.19 on 2021-07-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aparatur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('ttl', models.CharField(blank=True, max_length=100, null=True)),
                ('jk', models.CharField(blank=True, max_length=100, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=100, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('mulai_bekerja', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='')),
                ('bagian', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='budaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100)),
                ('lokasi', models.CharField(blank=True, max_length=200)),
                ('foto', models.FileField(blank=True, max_length=200, upload_to='budaya/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pariwisata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100)),
                ('lokasi', models.CharField(blank=True, max_length=200)),
                ('foto', models.FileField(blank=True, max_length=200, upload_to='wisata/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='penduduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nokk', models.CharField(max_length=20, null=True)),
                ('nik', models.CharField(max_length=20, null=True, unique=True)),
                ('nama', models.CharField(max_length=100, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('status_perkawinan', models.CharField(blank=True, max_length=50, null=True)),
                ('jk', models.CharField(blank=True, max_length=10, null=True)),
                ('alamat', models.CharField(blank=True, max_length=100, null=True)),
                ('pdd', models.CharField(blank=True, max_length=50, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100)),
                ('harga', models.PositiveIntegerField()),
                ('nama_penjual', models.CharField(blank=True, max_length=100, null=True)),
                ('no_wa', models.CharField(blank=True, max_length=100, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('foto', models.FileField(blank=True, max_length=200, upload_to='produk/')),
                ('author', models.CharField(max_length=100, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sturktur_aparatur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='')),
                ('tahun', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField(unique=True)),
                ('bagian', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='visi_misi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi', models.CharField(blank=True, max_length=100, null=True)),
                ('misi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
