# Generated by Django 2.2.19 on 2021-07-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_apbd_desa'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspek', models.PositiveIntegerField(blank=True, null=True)),
                ('spesimen', models.PositiveIntegerField(blank=True, null=True)),
                ('konfirmasi', models.PositiveIntegerField(blank=True, null=True)),
                ('sembuh', models.PositiveIntegerField(blank=True, null=True)),
                ('meninggal', models.PositiveIntegerField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='covid/')),
                ('author', models.CharField(max_length=150, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
