# Generated by Django 2.2.19 on 2021-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_covid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penduduk',
            old_name='pdd',
            new_name='pendidikan',
        ),
        migrations.RemoveField(
            model_name='penduduk',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='penduduk',
            name='dusun',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penduduk',
            name='rt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
