# Generated by Django 2.2.19 on 2021-07-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_auto_20210717_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='penduduk',
        ),
    ]
