# Generated by Django 2.2.19 on 2021-07-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_delete_penduduk'),
    ]

    operations = [
        migrations.CreateModel(
            name='penduduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nokk', models.CharField(max_length=20, null=True)),
                ('nik', models.CharField(max_length=20, null=True, unique=True)),
                ('nama', models.CharField(max_length=100, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('status_perkawinan', models.CharField(blank=True, max_length=50, null=True)),
                ('jk', models.CharField(blank=True, max_length=10, null=True)),
                ('alamat', models.CharField(blank=True, max_length=100, null=True)),
                ('rt', models.PositiveIntegerField(blank=True, null=True)),
                ('dusun', models.PositiveIntegerField(blank=True, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=50, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
