# Generated by Django 2.2.19 on 2021-07-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_penduduk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='alamat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
