# Generated by Django 2.2.19 on 2021-07-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_auto_20210717_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='sda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=256, null=True)),
                ('jumlah', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jenis', models.PositiveIntegerField()),
            ],
        ),
    ]
