# Generated by Django 2.2.19 on 2021-07-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_sda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sda',
        ),
    ]
