# Generated by Django 2.2.19 on 2021-07-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_sda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sda',
            name='tanggal',
            field=models.DateField(auto_now=True),
        ),
    ]
