# Generated by Django 2.2.19 on 2021-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0012_lembaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembaga',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lembaga',
            name='jumlah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
