# Generated by Django 2.2.19 on 2021-07-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0013_auto_20210719_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='prasarana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah', models.PositiveIntegerField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('jenis', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
