# Generated by Django 2.2.19 on 2021-07-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0016_informasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sturktur_aparatur',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='sturktur_aparatur',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sturktur_aparatur',
            name='tahun',
        ),
    ]
