# Generated by Django 2.2.19 on 2021-07-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0017_auto_20210724_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=255, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_diupload', models.DateField(auto_now_add=True)),
                ('tanggal_diperbaharui', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sturktur_aparatur',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='struktur/'),
        ),
    ]
