# Generated by Django 2.2.19 on 2021-07-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0018_auto_20210724_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='berita/'),
        ),
    ]
